# Generated by Django 5.0.4 on 2024-07-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10)),
                ('student_name', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
            ],
        ),
    ]
